### ISSUE TITLE
GLesmos breaks when toggled in the plugins menu

### ISSUE THREAD

**Issue by Fasteroid** [Fasteroid/DesModder#1]
https://github.com/DesModder/DesModder/pull/488

Not exactly sure if my branch introduced this issue or not, but it most-certainly needs fixing.

Toggling GLesmos off then back on via the plugin menu causes some kind of internal catastrophic failure.  It spits out a bunch of WebGL errors then dies:

![image](https://user-images.githubusercontent.com/29342750/217064056-525b1b44-a21b-47a0-b33f-df958c266252.png)

**Comment by jared-hughes** [comment]
It's not introduced by this branch, but probably worth fixing after the JFA line PR is merged since that affects a bunch of the relevant code.

I'll transfer to the main issue tracker.
