### ISSUE TITLE
Undeclared identifiers

### ISSUE THREAD

**Issue by jared-hughes** [Fasteroid/DesModder#6]
(After disabling the 2048 character limit:) The graph <https://www.desmos.com/calculator/cwol27id84> gives the following error. Works well on main branch.

```
[GLesmos Error] While compiling fragment shader:
      ERROR: 0:516: '_1786' : undeclared identifier
ERROR: 0:520: '_2308' : undeclared identifier
ERROR: 0:928: '_1801' : undeclared identifier
ERROR: 0:932: '_2323' : undeclared identifier
```

**Comment by Fasteroid** [comment]
[Loops inside outline derivatives seem broken.](https://www.desmos.com/calculator/unazq6qsvg)

**Comment by Fasteroid** [comment]
@jared-hughes Just tested on regular GLesmos branch without outlines and the problem still happens—taking the derivative of a summation or product causes the error.

Can we transfer this to DesModder main?

**Comment by jared-hughes** [comment]
Transferred
